name: Sync to Org Repository

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror to Org Repo
        run: |
          git config user.name "hsushuai"
          git config user.email "hsushuai@outlook.com"
          git remote add mirror https://x-access-token:${{ secrets.TEAMX_SYNC_ACTION }}@github.com/AI-Research-TeamX/SAP.git
          git push mirror --all --force
          git push mirror --tags --force
