name: Sync to Organization Repo

on:
  push:
    branches:
      - main  # 如果你的主分支是 master，请改成 master
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # 禁用默认身份

      - name: Remove default GitHub credentials
        run: git config --global --unset credential.helper || true

      - name: Mirror push to org repo
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote add target https://x-access-token:${{ secrets.TEAMX_SYNC_ACTION }}@github.com/AI-Research-TeamX/SAP.git
          git push target --mirror
